# Define the directories containing your source files
set SRC_DIR "./src"
set SIM_DIR "./sim"
set OUTPUT_PRJ "files.prj"

# Open the .prj file for writing
set prj_file [open $OUTPUT_PRJ w]
puts $prj_file "# Automatically generated by TCL script - [clock format [clock seconds] -format {%Y-%m-%d %H:%M:%S}]"
puts $prj_file ""

# Helper procedure to scan directories and write to the .prj file
proc add_files_to_prj {dir file_handle} {
    # Check if directory exists
    if {![file exists $dir]} {
        puts "Warning: Directory $dir does not exist. Skipping."
        return
    }

    # Find all HDL files in the directory
    set hdl_files [glob -nocomplain -directory $dir *.{v,sv,vhd,vhdl}]

    foreach file $hdl_files {
        set ext [file extension $file]
        
        # Determine the correct language keyword based on extension
        switch -nocase $ext {
            ".v" {
                puts $file_handle "verilog work \"$file\""
            }
            ".sv" {
                puts $file_handle "sv work \"$file\""
            }
            ".vhd" - ".vhdl" {
                puts $file_handle "vhdl xil_defaultlib \"$file\""
            }
        }
    }
}

# Scan your source and simulation directories
puts "Scanning for HDL files..."
add_files_to_prj $SRC_DIR $prj_file
add_files_to_prj $SIM_DIR $prj_file

# Close the file handle
close $prj_file
puts "Success: $OUTPUT_PRJ has been created!"
